### ISSUE TITLE
Crash "TypeError: object null is not iterable" for github/docs

### ISSUE THREAD

**Issue by nschonni** [igorshubovych/markdownlint-cli#112]
Was looking at setting up Markdownlint on the new 
Running the 0.24.0 version crashes with the following
```> markdownlint "**/*.md"

Z:\github-docs\node_modules\markdownlint\lib\markdownlint.js:859
      throw error;
      ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Z:\github-docs\node_modules\markdownlint\lib\md031.js:24:30
    at forMetadata (Z:\github-docs\node_modules\markdownlint\helpers\helpers.js:259:5)
    at Array.forEach (<anonymous>)
    at forEachLine (Z:\github-docs\node_modules\markdownlint\helpers\helpers.js:257:16)
    at Object.MD031 [as function] (Z:\github-docs\node_modules\markdownlint\lib\md031.js:18:5)
    at forRule (Z:\github-docs\node_modules\markdownlint\lib\markdownlint.js:595:20)
    at Array.forEach (<anonymous>)
    at lintContent (Z:\github-docs\node_modules\markdownlint\lib\markdownlint.js:641:14)
    at lintContentWrapper (Z:\github-docs\node_modules\markdownlint\lib\markdownlint.js:681:12)
    at lintFile (Z:\github-docs\node_modules\markdownlint\lib\markdownlint.js:687:5)
```
Rolling back to 0.23.2 runs without issue.

PS: @DavidAnson might be another good repo for the CITGM/CI setup after I get it running

**Comment by nschonni** [comment]
Sorry, just realized it is crashing on 0.23.2 as well, I had switched to markdown-cli2 after the initial crash. Trying to step back a few versions now to see if it is new issue or if I can find a particular file

**Comment by nschonni** [comment]
OK, one of the files that it's crashing on is https://github.com/github/docs/blob/main/content/admin/enterprise-management/differences-between-clustering-and-high-availability-ha.md

Stepping through the files to trace down to the individual files that are having the issues, the common point is nested codeblocks under ordered lists that have bad indenting. Some have closing backticks that aren't indented enough, or elements inside that are not indented enough. Can't figure out why the same thing is passing in latest CLI2, but failing in this one

**Comment by DavidAnson** [comment]
It doesn’t seem to cause an exception when pasted into https://dlaa.me/markdownlint/. Wonder if your install of CLI is somehow outdated?

**Comment by nschonni** [comment]
Same when pushing and running in CI https://github.com/nschonni/github-docs/actions/runs/307710095

**Comment by nschonni** [comment]
The fixes in https://github.com/nschonni/github-docs/commit/f2f62459ef14d590b85fa4a2afd95fdac5a61e28 did address it, but I found that there was a folder of "translations" masked in VS Code that I need to reapply the same formatting fixes to

**Comment by DavidAnson** [comment]
Both CLI and CLI2 are affected - however, CLI2 reports the error and continues linting while CLI aborts immediately. The following is information about affected files - seemingly all with the same issue. This will be an issue with https://github.com/DavidAnson/markdownlint, not either CLI project.

```
pi@pi:~/docs $ git remote -v
origin	https://github.com/github/docs.git (fetch)
origin	https://github.com/github/docs.git (push)
pi@pi:~/docs $ git rev-parse HEAD
56ffb1f5ed8612c13646e67f0e7144492b855191
pi@pi:~/docs $ cat cli2.txt | grep "threw an exception"
content/admin/enterprise-management/configuring-high-availability-replication-for-a-cluster.md:11
content/admin/installation/installing-github-enterprise-server-on-google-cloud-platform.md:11
content/admin/policies/creating-a-pre-receive-hook-environment.md:11
content/admin/policies/creating-a-pre-receive-hook-script.md:11
content/github/using-git/setting-your-username-in-git.md:11
translations/de-DE/content/admin/developer-workflow/creating-a-pre-receive-hook-environment.md:10
translations/de-DE/content/admin/developer-workflow/creating-a-pre-receive-hook-script.md:10
translations/de-DE/content/admin/enterprise-management/configuring-high-availability-replication-for-a-cluster.md:11
translations/de-DE/content/admin/installation/installing-github-enterprise-server-on-google-cloud-platform.md:11
translations/de-DE/content/admin/policies/creating-a-pre-receive-hook-environment.md:11
translations/de-DE/content/admin/policies/creating-a-pre-receive-hook-script.md:11
translations/de-DE/content/github/using-git/setting-your-username-in-git.md:11
translations/es-XL/content/admin/developer-workflow/creating-a-pre-receive-hook-environment.md:10
translations/es-XL/content/admin/developer-workflow/creating-a-pre-receive-hook-script.md:10
translations/es-XL/content/admin/enterprise-management/configuring-high-availability-replication-for-a-cluster.md:11
translations/es-XL/content/admin/installation/installing-github-enterprise-server-on-google-cloud-platform.md:11
translations/es-XL/content/admin/policies/creating-a-pre-receive-hook-environment.md:11
translations/es-XL/content/admin/policies/creating-a-pre-receive-hook-script.md:11
translations/es-XL/content/github/using-git/setting-your-username-in-git.md:11
translations/ja-JP/content/admin/developer-workflow/creating-a-pre-receive-hook-environment.md:10
translations/ja-JP/content/admin/developer-workflow/creating-a-pre-receive-hook-script.md:10
translations/ja-JP/content/admin/enterprise-management/configuring-high-availability-replication-for-a-cluster.md:11
translations/ja-JP/content/admin/installation/installing-github-enterprise-server-on-google-cloud-platform.md:11
translations/ja-JP/content/admin/policies/creating-a-pre-receive-hook-environment.md:11
translations/ja-JP/content/admin/policies/creating-a-pre-receive-hook-script.md:11
translations/ja-JP/content/github/using-git/setting-your-username-in-git.md:11
translations/ko-KR/content/admin/enterprise-management/configuring-high-availability-replication-for-a-cluster.md:11
translations/ko-KR/content/admin/installation/installing-github-enterprise-server-on-google-cloud-platform.md:11
translations/ko-KR/content/admin/policies/creating-a-pre-receive-hook-environment.md:11
translations/ko-KR/content/admin/policies/creating-a-pre-receive-hook-script.md:11
translations/ko-KR/content/github/using-git/setting-your-username-in-git.md:11
translations/pt-BR/content/admin/developer-workflow/creating-a-pre-receive-hook-environment.md:10
translations/pt-BR/content/admin/developer-workflow/creating-a-pre-receive-hook-script.md:10
translations/pt-BR/content/admin/enterprise-management/configuring-high-availability-replication-for-a-cluster.md:11
translations/pt-BR/content/admin/installation/installing-github-enterprise-server-on-google-cloud-platform.md:11
translations/pt-BR/content/admin/policies/creating-a-pre-receive-hook-environment.md:11
translations/pt-BR/content/admin/policies/creating-a-pre-receive-hook-script.md:11
translations/pt-BR/content/github/using-git/setting-your-username-in-git.md:11
translations/ru-RU/content/admin/enterprise-management/configuring-high-availability-replication-for-a-cluster.md:11
translations/ru-RU/content/admin/installation/installing-github-enterprise-server-on-google-cloud-platform.md:11
translations/ru-RU/content/admin/policies/creating-a-pre-receive-hook-environment.md:11
translations/ru-RU/content/admin/policies/creating-a-pre-receive-hook-script.md:11
translations/ru-RU/content/github/using-git/setting-your-username-in-git.md:11
translations/zh-CN/content/admin/developer-workflow/creating-a-pre-receive-hook-environment.md:10
translations/zh-CN/content/admin/developer-workflow/creating-a-pre-receive-hook-script.md:10
translations/zh-CN/content/admin/enterprise-management/configuring-high-availability-replication-for-a-cluster.md:11
translations/zh-CN/content/admin/installation/installing-github-enterprise-server-on-google-cloud-platform.md:11
translations/zh-CN/content/admin/policies/creating-a-pre-receive-hook-environment.md:11
translations/zh-CN/content/admin/policies/creating-a-pre-receive-hook-script.md:11
translations/zh-CN/content/github/using-git/setting-your-username-in-git.md:11
```

**Comment by nschonni** [comment]
OK, feel free to transfer the issue

**Comment by DavidAnson** [comment]
I can’t transfer because it’s a different organization. :) But don’t worry about it, this item is top of my list now. I may do a patch release for the library since this will be the second fix for a never-before-seen crash.

**Comment by nschonni** [comment]
Cool, might want to run it on github/docs, as I seem to recall there might have been a crash with MD039 too. That might have just been bad debugger attaching on my part in VS code 😆

**Comment by nschonni** [comment]
Cool! Chicken/egg thing. If a new release comes out, I may split that PR that includes the fixes to make it easier to land. There triage queue is a little overloaded right now, but here is the PR if you want to subscribe https://github.com/github/docs/pull/541

**Comment by DavidAnson** [comment]
I published a patch release of the library yesterday evening. At this point, fresh installs of the CLI _should_ install that release with the fix for this.

**Comment by nschonni** [comment]
I saw that, and had actually fixed that PR yesterday 😄 
I split out the content changes to a separate PR, but I'm waiting for their tech writers to review both the PRs
I'll go ahead an close this because it did fix the issue.

**Comment by DavidAnson** [comment]
You are too quick!

**Comment by nschonni** [comment]
Ha, I can ping you when that one lands if you aren't already subscribed to that PR

**Comment by DavidAnson** [comment]
I'm not subscribed - ping me. I'll add that repo to the tests.
