### ISSUE TITLE
SyntaxError: Unexpected token on run 

### ISSUE THREAD

**Issue by akhilesharora** [igorshubovych/markdownlint-cli#279]
Pre-commit config
```  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint

```
Output:
```
markdownlint.............................................................Failed
- hook id: markdownlint
- exit code: 1

/home/aarora/.cache/pre-commit/repomxj3cbbw/node_env-system/lib/node_modules/markdownlint-cli/markdownlint.js:50
    } catch {
            ^



SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
/home/aarora/.cache/pre-commit/repomxj3cbbw/node_env-system/lib/node_modules/markdownlint-cli/markdownlint.js:50
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3```

**Comment by DavidAnson** [comment]
Check if you're using a deprecated/unsupported version of Node, <12.

**Comment by akhilesharora** [comment]
Yeah, I only after upgrading to use 14, it worked, although couldn't find out from the documentation or maybe missed it somewhere, thanks ;)

**Comment by DavidAnson** [comment]
Node packages express their version via engines/node in package.json: https://github.com/igorshubovych/markdownlint-cli/blob/master/package.json#L9-L11
