### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by stevemart** [igorshubovych/markdownlint-cli#38]
Seems like running `markdownlint` the way I normally do has stopped working with the latest release of npm and/or node.

I looked at the line that's tossing up the error but it seems OK (https://github.com/DavidAnson/markdownlint/blob/master/lib/markdownlint.js#L161). I'll try a different (earlier) version of npm and see what happens.

```
$ node --version
v8.11.1
$ npm --version
5.6.0
$ markdownlint --version
0.8.1
$ markdownlint --config .markdownlint.json `ls -d */ | grep -v 'node_modules/'`
/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:161
      while (token.map[1] && !(lines[token.map[1] - 1].trim())) {
                                                       ^

TypeError: Cannot read property 'trim' of undefined
    at forToken (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:161:56)
    at Array.forEach (<anonymous>)
    at annotateTokens (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:144:10)
    at lintContent (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:298:3)
    at lintContentWrapper (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:413:5)
    at lintFile (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:418:5)
    at lintNextItem (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:474:9)
    at lintInput (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:488:3)
    at Function.markdownlintSync [as sync] (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:510:3)
    at lintAndPrint (/usr/local/lib/node_modules/markdownlint-cli/markdownlint.js:142:33)
```

**Comment by DavidAnson** [comment]
My guess is you are hitting this: https://github.com/DavidAnson/markdownlint/issues/117

Will be fixed soon - or you can remove the problematic LSEP characters.

If that is not it, please share steps to reproduce the error.

**Comment by stevemart** [comment]
@DavidAnson you're totally right, nasty bug! My issue was easily solved by removing the LSEP characters. I will close this bug. Feel free to re-open if you're tracking it, but from my point of view this is fine.

**Comment by DavidAnson** [comment]
Cool, thanks for letting me know!

**Comment by stevemart** [comment]
No problem, thanks for being such a responsive maintainer :)

**Comment by timph** [comment]
We just can't remove them in many of our generated mdx files. Is there a workaround for this issue?

**Comment by DavidAnson** [comment]
The fix discussed above (4 years ago?) should be in recent builds. Can you please give an example of what's not working for you? A link to a file in a repo is especially useful.

**Comment by timph** [comment]
Oops, my bad @DavidAnson . It's 'markdownlint-cli' that pulls in old 'markdowlint'. I'll update that `markdownlint-cli` version.
