### ISSUE TITLE
Error: Cannot find module 'node:fs'

### ISSUE THREAD

**Issue by coanor** [igorshubovych/markdownlint-cli#390]
I've install the latest version:

```shell
$ sudo  npm install -g markdownlint-cli
/usr/local/bin/markdownlint -> /usr/local/lib/node_modules/markdownlint-cli/markdownlint.js
npm WARN notsup Unsupported engine for markdownlint-cli@0.33.0: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: markdownlint-cli@0.33.0
npm WARN notsup Unsupported engine for commander@9.4.1: wanted: {"node":"^12.20.0 || >=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: commander@9.4.1
npm WARN notsup Unsupported engine for get-stdin@9.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: get-stdin@9.0.0
npm WARN notsup Unsupported engine for glob@8.0.3: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: glob@8.0.3
npm WARN notsup Unsupported engine for markdownlint@0.27.0: wanted: {"node":">=14.18.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: markdownlint@0.27.0
npm WARN notsup Unsupported engine for ini@3.0.1: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: ini@3.0.1

+ markdownlint-cli@0.33.0
updated 1 package in 5.415s
```

When try to run the command, I got the error:

``` shell
$ markdownlint -h
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:fs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/markdownlint-cli/markdownlint.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by nschonni** [comment]
From the error, you're running Node 10, that isn't supported, and is EOL by several years

**Comment by coanor** [comment]
> From the error, you're running Node 10, that isn't supported, and is EOL by several years

Yes, I just install `npm` in my Ubuntu 20.04, can't beleave its such a old version.

**Comment by DavidAnson** [comment]
As I recall, the Ubuntu apt packages for Node are not updated. You will need to install via directions on Node site to get a current version.

**Comment by coanor** [comment]
After [upgrade to 18.x](https://github.com/nodesource/distributions#using-ubuntu-2), it works now.
