### ISSUE TITLE
cli `markdownlint --help` fails out of the box

### ISSUE THREAD

**Issue by dfarrel1** [igorshubovych/markdownlint-cli#57]
after install 
`npm install -g markdownlint-cli`

testing the cli 
`markdownlint --help`

returns an error.
```
/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:262
      capturedRules = { ...enabledRules };
                        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/markdownlint-cli/markdownlint.js:14:22)
```

**Comment by nschonni** [comment]
Are you running an older version of Node that doesn't understand rest parameters?

**Comment by DavidAnson** [comment]
FYI, this project advertises a minimum supported Node version of 8 - earlier version are out of support by the Node team.

CI is passing on Node versions 8-12: https://travis-ci.org/igorshubovych/markdownlint-cli

**Comment by DavidAnson** [comment]
Info about supported Node versions: https://nodejs.org/en/about/releases/

Minimum version declaration: https://github.com/igorshubovych/markdownlint-cli/blob/c5b314bd580ebd83980a620a54745bf34aa3d167/package.json#L10
