### ISSUE TITLE
Bug: Can't handle absolute paths

### ISSUE THREAD

**Issue by noelmace** [igorshubovych/markdownlint-cli#79]
When using `lint-staged`, I get the following error from `node-ignore`:

```
RangeError: path should be a `path.relative()`d string, but got "/data/git/project/src/1._directory/file.md"
  at throwError (/data/git/project/node_modules/ignore/index.js:337:9)
  at checkPath (/data/git/project/node_modules/ignore/index.js:356:12)
  at Ignore._test (/data/git/project/node_modules/ignore/index.js:473:5)
  at Ignore.ignores (/data/git/project/node_modules/ignore/index.js:512:17)
  at ignoreFilter (/data/git/project/node_modules/markdownlint-cli/markdownlint.js:238:28)
  at Array.filter (<anonymous>)
  at Object.<anonymous> (/data/git/project/node_modules/markdownlint-cli/markdownlint.js:243:4)
  at Module._compile (internal/modules/cjs/loader.js:1151:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
  at Module.load (internal/modules/cjs/loader.js:1000:32)
```

## Configuration

nodejs: v13.9.0
OS: Manjaro Linux
shell: zsh
markdownlint-cli: v0.22.0

### .markdownlintignore

```ignore
node_modules
build
dist
/src/.vuepress
/refs
.vscode
.github
CHANGELOG.md
definitions.md
/src/refs/biblio.md
```
### lint-staged (in package.json)

```json
{
  "lint-staged": {
    "*.md": [
      "prettier --write",
      "markdownlint --fix"
    ],
    "*.{js,css,html}": [
      "prettier --write"
    ]
  }
}
```

May be related to #31
I will create a PR for that very soon.

**Comment by DavidAnson** [comment]
FYI, unlikely to be related to #31 because that code does not use the `ignore` module (it was written before it was introduced). Also, that issue was fixed and tests added.

**Comment by jdanil** [comment]
Hi @DavidAnson, any plans to trigger a release for this change?
Facing the same issue trying to integrate with lint-staged.

**Comment by DavidAnson** [comment]
Yep, publishing a new CLI is next on my list. (I had to go back and patch an issue in the library first.)

**Comment by jdanil** [comment]
Awesome. Thanks for the update 🙂
