### ISSUE TITLE
TypeError: content.trimEnd is not a function

### ISSUE THREAD

**Issue by MartinPetkov** [igorshubovych/markdownlint-cli#90]
Since version 0.23.0, released on May 5, 1:00am EDT (2020-05-05T04:52:03.666Z), we are seeing this error in our presubmit job:
```
/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:799
      throw error;
      ^

TypeError: content.trimEnd is not a function
    at handleRunEnd (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:38:27)
    at MD037.forEachLine (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:133:13)
    at forMetadata (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:256:5)
    at Array.forEach (<anonymous>)
    at forEachLine (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:254:16)
    at Object.MD037 [as function] (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:71:5)
    at forRule (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:593:20)
    at Array.forEach (<anonymous>)
    at lintContent (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:639:14)
    at lintContentWrapper (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:679:12)
```

This is from a shell script running GCB (Google Cloud Build). The GCB yaml looks like this:
```
steps:
- name: "gcr.io/cloud-builders/npm"
  entrypoint: "sh"
  args: ["build/md_check.sh"]
```

And `md_check.sh` is this:
```
#!/bin/bash
set -e
npm install -g markdownlint-cli
markdownlint **/*.md
```

**Comment by DavidAnson** [comment]
What version of Node.js?

**Comment by DavidAnson** [comment]
And can you please share a file that demonstrates the problem?

**Comment by DavidAnson** [comment]
This release was semver-breaking; I see you’ve updated your precondition script accordingly, thanks!

https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/34

**Comment by MartinPetkov** [comment]
Here are reproduction steps:
```
$ docker run -it --entrypoint=bash gcr.io/cloud-builders/npm

root@ad6885b54b2d:/# npm --version
6.4.1

root@ad6885b54b2d:/# npm install -g markdownlint-cli
/usr/local/bin/markdownlint -> /usr/local/lib/node_modules/markdownlint-cli/markdownlint.js
+ markdownlint-cli@0.23.0
added 36 packages from 28 contributors in 2.331s

root@ad6885b54b2d:/# git clone https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/

root@ad6885b54b2d:/# cd healthcare-data-protection-suite/

root@ad6885b54b2d:/healthcare-data-protection-suite# markdownlint **/*.md
/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:799
      throw error;
      ^

TypeError: content.trimEnd is not a function
    at handleRunEnd (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:38:27)
    at MD037.forEachLine (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:133:13)
    at forMetadata (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:256:5)
    at Array.forEach (<anonymous>)
    at forEachLine (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:254:16)
    at Object.MD037 [as function] (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:71:5)
    at forRule (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:593:20)
    at Array.forEach (<anonymous>)
    at lintContent (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:639:14)
    at lintContentWrapper (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:679:12)
```

**Comment by DavidAnson** [comment]
Thanks, I’ll try this repro after work today. Can you please confirm the version of Node.js that you are using? I don’t see it in the output above.

**Comment by MartinPetkov** [comment]
Right, sorry:
```
root@31af13dc060f:/# node --version
v8.12.0
```

**Comment by DavidAnson** [comment]
Node.js 8 is no longer supported due to being end-of-life: https://nodejs.org/en/about/releases/

That API is not present in Node 8: https://node.green/#ES2019-features-string-trimming-String-prototype-trimEnd

The CLI advertises a minimum version of Node 10: https://github.com/igorshubovych/markdownlint-cli/blob/3b7ec124c66d3229aa1490e8d31cbddb2bfae05f/package.json#L10

**Comment by MartinPetkov** [comment]
Thank you, we'll update our scripts to use a Node 10 container.

**Comment by MartinPetkov** [comment]
I'm going to close this, as it's an issue on our side (using an unsupported version of Node).

**Comment by DavidAnson** [comment]
Thanks!
